print("Welcome to Tip Calculator")
bill  = float(input("What was the total bill? $"))
tip   = int(input("How much tip would you like to give? 10, 12, 15? "))
split = int(input("How many people should split the bill? "))
percentage_tip = float(tip / 100)
total_tip =float(bill * percentage_tip)
total_bill = float((bill + total_tip) / split)
final_bill = round(total_bill, 2)
print(f"Each person should pay: ${final_bill} ")