question_data = [{"category": "Vehicles", "type": "boolean", "difficulty": "hard",
                  "question": "In 1993 Swedish car manufacturer Saab experimented with replacing the steering wheel with a joystick in a Saab 9000.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Han Solo&#039;s co-pilot and best friend, &quot;Chewbacca&quot;, is an Ewok.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The Great Wall of China is visible from the moon.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "The surface area of Russia is slightly larger than that of the dwarf planet Pluto.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "&quot;Undertale&quot; is an RPG created by Toby Fox and released in 2015.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Board Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In the game &quot;Racko&quot; you may pick up ANY card from the discard pile.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "Assyrian king Sennacherib&#039;s destruction of Babylon in 689 BCE was viewed as a triumph by other Assyrian citizens.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean",
                  "difficulty": "easy",
                  "question": "A universal set, or a set that contains all sets, exists.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Big the Cat is a playable character in &quot;Sonic Generations&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "easy",
                  "question": "Denmark has a monarch.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "United States President John F. Kennedy was assassinated during his presidential motorcade in Atlanta, Georgia on November 22nd, 1963.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "In 1967, a magazine published a story about extracting hallucinogenic chemicals from bananas to raise moral questions about banning drugs.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Japanese Anime & Manga",
                  "type": "boolean", "difficulty": "easy",
                  "question": "In the &quot;Melancholy of Haruhi Suzumiya&quot; series, the narrator goes by the nickname Kyon.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Television", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In the TV series Red Dwarf, Kryten&#039;s full name is Kryten 2X4B-523P.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "hard",
                  "question": "DHCP stands for Dynamic Host Configuration Port.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In the game &quot;Subnautica&quot;, a &quot;Spadefish&quot; will attack you.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "hard",
                  "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Gadgets", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Microphones can be used not only to pick up sound, but also to project sound similar to a speaker.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "hard",
                  "question": "The names of Roxas&#039;s Keyblades in Kingdom Hearts are &quot;Oathkeeper&quot; and &quot;Oblivion&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In the game Dead by Daylight, the killer Michael Myers is refered to as &quot;The Shape&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "medium",
                  "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean",
                  "difficulty": "hard",
                  "question": "The band STRFKR was also briefly known as Pyramiddd.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "Oxford University is older than the Aztec Empire. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The Konami Code is known as Up, Up, Down, Down, Left, Right, Right, Left, B, A, Start.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean",
                  "difficulty": "easy", "question": "Daft Punk originated in France.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "Adolf Hitler was accepted into the Vienna Academy of Fine Arts.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Linux was first created as an alternative to Windows XP.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "hard",
                  "question": "The USS Missouri (BB-63) last served in the Korean War.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean",
                  "difficulty": "medium",
                  "question": "A &#039;Millinillion&#039; is a real number.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In Heroes of the Storm, the Cursed Hollow map gimmick requires players to kill the undead to curse the enemy team.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In &quot;Super Mario World&quot;, the rhino mini-boss, Reznor, is named after the lead singer of the band &quot;Nine Inch Nails&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "easy",
                  "question": "An average human can go two weeks without water.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean",
                  "difficulty": "hard",
                  "question": "In Topology, the complement of an open set is a closed set.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Board Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "&quot;Rich Uncle Pennybags&quot; from the board game &quot;Monopoly&quot; wears a monocle.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga",
                  "type": "boolean", "difficulty": "medium",
                  "question": "In &quot;To Love-Ru: Darkness&quot;, Yami reveals her real name is Eve.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Scotland voted to become an independent country during the referendum from September 2014.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "New Haven is the capital city of the state of Connecticut in the United States.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean",
                  "difficulty": "medium",
                  "question": "You can square root a negative number with an imaginary number &quot;i&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Television", "type": "boolean",
                  "difficulty": "medium",
                  "question": "An episode of &quot;The Simpsons&quot; is dedicated to Moe Szyslak&#039;s bar rag.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In the &quot;S.T.A.L.K.E.R.&quot; series, the Freedom faction wishes to destroy the supernatural area known as  &quot;the Zone&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Water always boils at 100&deg;C, 212&deg;F, 373.15K, no matter where you are.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Sound can travel through a vacuum.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean",
                  "difficulty": "medium",
                  "question": "A Facebook campaign placed Rage Against The Machine&#039;s &quot;Killing in the Name Of&quot; as the UK Christmas Number 1 in 2009.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "A pasodoble is a type of Italian pasta sauce.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean",
                  "difficulty": "easy",
                  "question": "John Williams composed the music for &quot;Star Wars&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Shang Tsung is a playable character in Mortal Kombat XL.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "hard",
                  "question": "NCIS stands for &quot;Navy Corps Investigative Service&quot;",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The shotgun appears in every numbered Resident Evil game.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
